### PR TITLE
links updated in navbar

### PR DESCRIPTION
**Pull request by vsasvipul0605**

### CODE REVIEW

**Review by Yashank18 — COMMENTED** [review]
Hey, I just saw the changes you have made in this PR but I don't think there is a need for them. Have you come across any issues regarding the same?

**Comment by xlogix** [comment]
@Yashank18 Exactly my thoughts

**Comment by vsasvipul0605** [comment]
I cloned and set up locally that wasn't working then 
Screenshot (127)
that's why I updated those.

**Comment by xlogix** [comment]
Oh yes, they don't work locally but work after deployment.

**Pull request closed without merging**
